//
// TCG Template for Typst
// Initial version generated by Pandoc v3.6.4 using:
//   pandoc -D typst
//

//
// TODO: Title page
//

//
// Font settings
//
// Normal text
#set text(
  font: "Noto Sans",
  size: 9pt,
)
// Math
#show math.equation: set text(
  font: "Noto Sans Math",
  size: 9pt,
)
// Code
#show raw: set text(
  font: "Noto Sans Mono",
  size: 9pt,
)
// Headings
#set heading(numbering: "1.1")
#show heading: it => block()[
  #let size = 16pt - it.depth*2pt
  #if size < 10pt { size = 10pt }
  #set align(center)
  #set text(
    font: "Noto Sans",
    size: size,
    weight: "semibold")
  #it
]

#let horizontalrule = line(start: (25%,0%), end: (75%,0%))

#show terms: it => {
  it.children
    .map(child => [
      #strong[#child.term]
      #block(inset: (left: 1.5em, top: -0.4em))[#child.description]
      ])
    .join()
}

#set table(
  inset: 6pt,
  stroke: 1pt
)

#show figure.where(
  kind: table
): set figure.caption(position: bottom)

#show figure.where(
  kind: image
): set figure.caption(position: bottom)

$if(toc)$
#outline(
  title: auto,
  depth: $toc-depth$
);
$endif$

$body$

$if(citations)$
$if(csl)$

#set bibliography(style: "$csl$")
$elseif(bibliographystyle)$

#set bibliography(style: "$bibliographystyle$")
$endif$
$if(bibliography)$

#bibliography($for(bibliography)$"$bibliography$"$sep$,$endfor$)
$endif$
$endif$
$for(include-after)$

$include-after$
$endfor$
