# Reminder: Due to the way GitHub Actions treats reusable workflows that use reusable actions from local paths,
# we have to update .github/workflows/render.yml to point to a particular commit of this file.
# This means that when updating this file, we have to first send a PR that updates the action,
# then second send a PR send that uses the action in the reusable workflow.

name: 'Render'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-basename:
    description: 'The base name (without extension) to use for output file(s)'
    required: true
  pr-repo:
    description: 'Pull request repo (use with pr-number)'
    required: false
    type: 'string'
  pr-number:
    description: 'Pull request number to reference (use with pr-repo)'
    required: false
    type: 'string'
  pdf:
    description: 'Render to PDF'
    required: false
    type: 'boolean'
    default: 'true'
  diffbase:
    description: 'The revision to diff against (use with pdf)'
    required: false
    type: 'string'
  html:
    description: 'Render to HTML'
    required: false
    type: 'boolean'
    default: 'false'
  docx:
    description: 'Render to Word'
    required: false
    type: 'boolean'
    default: 'false'
  tex:
    description: 'Render to TeX'
    required: false
    type: 'boolean'
    default: 'false'
  extra-build-options:
    description: 'Additional build options to be passed to build.sh'
runs:
  using: 'composite'
  steps:
    # let the container take ownership of the repo dir, in case the user wants to check in the results
    # workaround to https://github.com/actions/runner/issues/2033
    - run: chown -R $(id -u):$(id -g) $PWD
      shell: sh
    - run: >
        /usr/bin/build.sh
        --versioned_filenames
        $( [ -n "${{ inputs.pr-repo }}" -a -n "${{ inputs.pr-number }}" ]   && echo --pr_number=${{ inputs.pr-number }} --pr_repo=${{ inputs.pr-repo }} )
        $( [ ${{ inputs.pdf }} -a -n "${{ inputs.diffbase }}" ]             && echo --diffbase=${{ inputs.diffbase }} --diffpdf=${{ inputs.output-basename }}.diff.pdf --difftex=${{ inputs.output-basename }}.diff.tex --diffpdflog=${{ inputs.output-basename }}.diff.pdf.log )
        $( ${{ inputs.pdf }}                                                && echo --pdf=${{ inputs.output-basename }}.pdf --pdflog=${{ inputs.output-basename }}.pdf.log )
        $( ${{ inputs.html }}                                               && echo --html=${{ inputs.output-basename }}.html )
        $( ${{ inputs.docx }}                                               && echo --docx=${{ inputs.output-basename }}.docx )
        $( ${{ inputs.tex }}                                                && echo --latex=${{ inputs.output-basename }}.tex )
        ${{ inputs.extra-build-options }}
        ${{ inputs.input-md }}
      shell: sh
