name: manual

on:
  workflow_dispatch:
    inputs:
      revision:
        description: the version or commit to render (if left empty, uses default branch)
        required: false
        type: string
      diffbase:
        description: the version or commit to diff against (if left empty, no diff is generated)
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Use the latest container to render the samples with the given diff
  render-samples:
    uses: ./.github/workflows/render.yml
    with:
      container-version: latest
      input: guide.tcg
      workflow: manual
      manual_diffbase: ${{ inputs.diffbase }}
      revision: ${{ inputs.revision }}
