name: render samples

on:
  push:
    branches: main
  pull_request:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Build a fresh container for the PR.
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image as "pandoc_test"
      # Only amd64, since we're just building a container
      # to be used below in the GH action runner.
      - name: Build and publish Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Cache layers from the container repo.
          # This minimizes the amount of times we have to rebuild pandoc.
          # Read-only: Avoid cluttering up the cache on pull requests.
          cache-from: type=gha
          platforms: linux/amd64
          push: true
          tags: ghcr.io/trustedcomputinggroup/pandoc_test

  render-samples:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trustedcomputinggroup/pandoc_test
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Run the action on guide
        uses: trustedcomputinggroup/markdown@latest
        with:
          extra-build-options: "--gitstatus --plain_quotes"
          input-md: guide.md
          output-pdf: guide.pdf
          output-tex: guide.tex
          output-docx: guide.docx

      - name: Upload PDF
        uses: actions/upload-artifact@master
        with:
          name: PDF
          path: guide.pdf

      - name: Upload TeX
        uses: actions/upload-artifact@master
        with:
          name: TeX
          path: guide.tex

      - name: Upload Docx
        uses: actions/upload-artifact@master
        with:
          name: Word
          path: guide.docx

