name: render samples

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Build a fresh container for the PR.
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image as "pandoc_test"
      # Only amd64, since we're just building a container
      # to be used below in the GH action runner.
      - name: Build and publish Docker image
        uses: docker/build-push-action@v5
        with:
          # Cache layers from the container repo.
          # This minimizes the amount of times we have to rebuild pandoc.
          # Read-only: Avoid cluttering up the cache on pull requests.
          cache-from: type=gha
          platforms: linux/amd64
          push: true
          tags: ghcr.io/trustedcomputinggroup/pandoc_test

  render-samples:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trustedcomputinggroup/pandoc_test
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-tags: true

      - name: Cache LaTeX files
        uses: actions/cache@v3
        env:
          cache-name: cache-latex-files
        with:
          path: |
            *.aux
            *.fdb_latexmk
            *.lof
            *.lot
            *.toc
            *.upa
            *.upb
            *.convert.pdf
          key: latex-${{ github.run_id }}
          restore-keys: latex

      - name: Run the action on guide
        uses: ./.github/actions/render
        with:
          input-md: guide.tcg
          output-basename: guide
          pdf: true
          tex: true
          docx: true
          diffbase: "${{ github.event.pull_request.base.sha }}"
          pr-number: "${{ github.event.number }}"
          pr-repo: "${{ github.repository }}"

      - name: Upload PDF
        uses: actions/upload-artifact@master
        with:
          name: PDF
          path: guide.*.pdf

      - name: Upload logs
        uses: actions/upload-artifact@master
        with:
          name: Logs
          path: guide.*.log

      - name: Upload TeX
        uses: actions/upload-artifact@master
        with:
          name: TeX
          path: guide.*.tex

      - name: Upload Docx
        uses: actions/upload-artifact@master
        with:
          name: Word
          path: guide.*.docx

